### ISSUE TITLE
请问能考虑一下 mac 用户的快捷键吗？

### ISSUE THREAD

**Issue by yuanfoudev** [gantFDT/icraft#10]
目前所有快捷键方式都是通过 ctrl 来触发...

**Comment by yuanguandong** [comment]
> 目前所有快捷键方式都是通过 ctrl 来触发...

好的，下个版本优化下这个问题，顺便做个调研：“如果快捷键支持自定义会不会更好？您觉得iCraft Editor有必要提供快捷键自定义功能吗？”

**Comment by yuanfoudev** [comment]
能够自定义当然好，不过还是建议在 pwa 上做适配，目前怎么低成本怎么来比较合适，如果连 cmd+s 都无法保存的话，确实有点难以迈过初期曲线。

**Comment by yuanguandong** [comment]
快捷键已完善，可以再试试，
![image](https://github.com/user-attachments/assets/760b13bd-8906-4481-a553-70820307b587)
https://icraft.gantcloud.com/editor
