### ISSUE TITLE
Mac Intel 版本使用起来很卡是网络差还是电脑配置不行呢

### ISSUE THREAD

**Issue by lry151** [gantFDT/icraft#13]

**Comment by yuanguandong** [comment]
场景是否有上传自定义的3D模型？如果场景中有比较复杂的3D模型的时候，可能会导致显存过高引起卡顿

**Comment by lry151** [comment]
> 场景是否有上传自定义的3D模型？如果场景中有比较复杂的3D模型的时候，可能会导致显存过高引起卡顿

没有呢，就正常使用，拖动模型的时候要转圈好久

**Comment by yuanguandong** [comment]
> > 场景是否有上传自定义的3D模型？如果场景中有比较复杂的3D模型的时候，可能会导致显存过高引起卡顿
> 
> 没有呢，就正常使用，拖动模型的时候要转圈好久

方便把文件发我排查下吗？

**Comment by lry151** [comment]
> > > 场景是否有上传自定义的3D模型？如果场景中有比较复杂的3D模型的时候，可能会导致显存过高引起卡顿
> > 
> > 
> > 没有呢，就正常使用，拖动模型的时候要转圈好久
> 
> 方便把文件发我排查下吗？

文件删除掉了，刚刚新建一个文件，使用了一下不卡了，可能是昨天网络太卡了加上开了 VPN 的缘故，现在能正常使用了，辛苦回复了
