### ISSUE TITLE
有前端组件或vue可用的组件发布计划时间吗？

### ISSUE THREAD

**Issue by renqiankun** [gantFDT/icraft#8]

**Comment by yuanguandong** [comment]
目前react版本组件已正式发布：https://icraft.gantcloud.com/player-react/intro，可以轻松地将 iCraft Editor 编辑的场景集成到您的项目中， 并提供丰富的交互事件和方法。欢迎试用！

纯js版本的组件以及Vue版的组件还没确定具体的发布时间，敬请期待！

**Comment by yuanguandong** [comment]
> > 目前react版本组件已正式发布：[https://icraft.gantcloud.com/player-react/intro，可以轻松地将](https://icraft.gantcloud.com/player-react/intro%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%BD%BB%E6%9D%BE%E5%9C%B0%E5%B0%86) iCraft Editor 编辑的场景集成到您的项目中， 并提供丰富的交互事件和方法。欢迎试用！
> > 纯js版本的组件以及Vue版的组件还没确定具体的发布时间，敬请期待！
> 
> 通过iframe集成时，连接只能是https://icraft.gantcloud.com/editor 这个吗？ 没有可以部署到内部的包吗？

对，iframe 集成时只能是 https://icraft.gantcloud.com/editor

**Comment by yuanguandong** [comment]
> _No description provided._

hi, 原生javascript版本的player现已发布，可以试试 ：https://icraft.gantcloud.com/zh-CN/player-javascript/intro
